#!/usr/bin/env python3
"""Classify Gaussian IRC endpoints with the ReactBench Intended criterion.

The two IRC endpoints are read directly from ``irc.log``.  The expected
reactant and product must be supplied as a two-frame XYZ in ReactBench order.
Connectivity is generated by ReactBench's own ``table_generator`` so its
distance/radius, H-H, and maximum-valence behavior stays authoritative.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Callable, Sequence

import numpy as np


DEFAULT_REACTBENCH_ROOT = Path("/home/wuping/GitHub/ReactBench/ReactBench")
EXPECTED_REACTBENCH_CLASSIFIER_SHA256 = "86d9ae9414dff315073792dcb97e04f3aa169c2d33c564a77df00af837851119"
EXPECTED_REACTBENCH_TABLE_GENERATOR_SHA256 = "3cf210b3b3b898b123d4e1c27fe02c2c066d52dafbca1acba504297e2ca5031d"
IGNORE_ELEMENTS = frozenset({"zn", "mg", "li", "si", "ag", "cu", "b"})
POINT_RE = re.compile(
    r"Point\s+Number\s+(\d+)\s+in\s+(FORWARD|REVERSE)\s+path\s+direction\.",
    re.IGNORECASE,
)

# Index is atomic number.  Only reference-element validation uses this table;
# ReactBench remains authoritative for radii and adjacency generation.
PERIODIC_SYMBOLS = (
    "", "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na",
    "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti",
    "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As",
    "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru",
    "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs",
    "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy",
    "Ho", "Er", "Tm", "Yb", "Lu", "Hf", "Ta", "W", "Re", "Os", "Ir",
    "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra",
    "Ac", "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es",
    "Fm", "Md", "No", "Lr", "Rf", "Db", "Sg", "Bh", "Hs", "Mt", "Ds",
    "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og",
)
ATOMIC_NUMBER = {symbol.lower(): number for number, symbol in enumerate(PERIODIC_SYMBOLS) if symbol}


class ClassificationError(RuntimeError):
    """Raised when endpoint identity cannot be classified safely."""


@dataclass(frozen=True)
class Geometry:
    elements: tuple[str, ...]
    atomic_numbers: tuple[int, ...]
    coordinates: np.ndarray


@dataclass(frozen=True)
class IrcEndpoint:
    direction: str
    point_number: int
    atomic_numbers: tuple[int, ...]
    coordinates: np.ndarray


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def normalize_symbol(raw: str) -> str:
    symbol = raw.strip()
    if not symbol:
        raise ClassificationError("empty element symbol in reference XYZ")
    symbol = symbol[0].upper() + symbol[1:].lower()
    if symbol.lower() not in ATOMIC_NUMBER:
        raise ClassificationError(f"unsupported element symbol in reference XYZ: {raw!r}")
    return symbol


def read_two_frame_xyz(path: Path) -> tuple[Geometry, Geometry]:
    """Read exactly two standard XYZ frames: expected reactant, then product."""
    if not path.is_file():
        raise ClassificationError(f"reference XYZ not found: {path}")
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    frames: list[Geometry] = []
    cursor = 0
    while cursor < len(lines):
        while cursor < len(lines) and not lines[cursor].strip():
            cursor += 1
        if cursor >= len(lines):
            break
        try:
            atom_count = int(lines[cursor].strip())
        except ValueError as exc:
            raise ClassificationError(
                f"invalid XYZ atom-count line {cursor + 1}: {lines[cursor]!r}"
            ) from exc
        cursor += 1
        if cursor >= len(lines):
            raise ClassificationError("XYZ frame is missing its comment line")
        cursor += 1  # comment line, including an intentionally blank comment
        elements: list[str] = []
        coordinates: list[list[float]] = []
        for _ in range(atom_count):
            if cursor >= len(lines):
                raise ClassificationError("truncated XYZ coordinate block")
            fields = lines[cursor].split()
            cursor += 1
            if len(fields) < 4:
                raise ClassificationError(f"invalid XYZ coordinate line: {lines[cursor - 1]!r}")
            elements.append(normalize_symbol(fields[0]))
            try:
                coordinates.append([float(fields[1]), float(fields[2]), float(fields[3])])
            except ValueError as exc:
                raise ClassificationError(f"invalid XYZ coordinates: {fields[1:4]!r}") from exc
        atomic_numbers = tuple(ATOMIC_NUMBER[element.lower()] for element in elements)
        frames.append(
            Geometry(tuple(elements), atomic_numbers, np.asarray(coordinates, dtype=float))
        )
    if len(frames) != 2:
        raise ClassificationError(
            f"expected exactly two XYZ frames (reactant, product), found {len(frames)}"
        )
    if frames[0].elements != frames[1].elements:
        raise ClassificationError("reactant/product XYZ atom order or elements differ")
    return frames[0], frames[1]


def _read_orientation(handle: Any) -> tuple[tuple[int, ...], np.ndarray]:
    """Consume a Gaussian Input-orientation table after its heading line."""
    dashed = 0
    atoms: list[int] = []
    coordinates: list[list[float]] = []
    for line in handle:
        if line.strip().startswith("-----"):
            dashed += 1
            if dashed >= 3:
                break
            continue
        if dashed != 2:
            continue
        fields = line.split()
        if len(fields) < 6:
            continue
        try:
            atomic_number = int(fields[1])
            xyz = [float(fields[3]), float(fields[4]), float(fields[5])]
        except ValueError as exc:
            raise ClassificationError(f"malformed Gaussian orientation row: {line.rstrip()!r}") from exc
        atoms.append(atomic_number)
        coordinates.append(xyz)
    if not atoms:
        raise ClassificationError("empty or truncated Gaussian Input orientation")
    return tuple(atoms), np.asarray(coordinates, dtype=float)


def read_gaussian_irc_endpoints(path: Path) -> tuple[IrcEndpoint, IrcEndpoint, dict[str, bool]]:
    """Return the largest-numbered FORWARD and REVERSE IRC point geometries."""
    if not path.is_file():
        raise ClassificationError(f"IRC log not found: {path}")
    endpoints: dict[str, IrcEndpoint] = {}
    current_direction: str | None = None
    current_point: int | None = None
    flags = {
        "forward_path_complete_printed": False,
        "reverse_path_complete_printed": False,
        "reaction_path_complete_printed": False,
        "normal_termination_printed": False,
    }
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            match = POINT_RE.search(line)
            if match:
                current_point = int(match.group(1))
                current_direction = match.group(2).upper()
                continue
            if "Calculation of FORWARD path complete." in line:
                flags["forward_path_complete_printed"] = True
                current_direction = None
                current_point = None
                continue
            if "Calculation of REVERSE path complete." in line:
                flags["reverse_path_complete_printed"] = True
                current_direction = None
                current_point = None
                continue
            if "Reaction path calculation complete." in line:
                flags["reaction_path_complete_printed"] = True
            if "Normal termination of Gaussian" in line:
                flags["normal_termination_printed"] = True
            if current_direction and "Input orientation:" in line:
                atomic_numbers, coordinates = _read_orientation(handle)
                previous = endpoints.get(current_direction)
                if previous is None or current_point is not None and current_point >= previous.point_number:
                    endpoints[current_direction] = IrcEndpoint(
                        current_direction,
                        int(current_point),
                        atomic_numbers,
                        coordinates,
                    )
    missing = [direction for direction in ("FORWARD", "REVERSE") if direction not in endpoints]
    if missing:
        raise ClassificationError(f"missing IRC point geometry for: {', '.join(missing)}")
    return endpoints["FORWARD"], endpoints["REVERSE"], flags


@lru_cache(maxsize=None)
def load_reactbench_table_generator(
    reactbench_root: Path,
) -> tuple[Callable[..., np.ndarray], Path, Path]:
    """Load the authoritative ReactBench adjacency implementation."""
    module_file = reactbench_root / "utils/taffi_functions.py"
    classifier_file = reactbench_root / "main_functions.py"
    if not module_file.is_file():
        raise ClassificationError(f"ReactBench table_generator not found: {module_file}")
    if not classifier_file.is_file():
        raise ClassificationError(f"ReactBench Intended classifier source not found: {classifier_file}")
    observed_classifier_hash = sha256(classifier_file)
    observed_table_hash = sha256(module_file)
    if observed_classifier_hash != EXPECTED_REACTBENCH_CLASSIFIER_SHA256:
        raise ClassificationError(
            "ReactBench main_functions.py changed; review the Intended branches and update the "
            f"frozen hash before use (observed {observed_classifier_hash})"
        )
    if observed_table_hash != EXPECTED_REACTBENCH_TABLE_GENERATOR_SHA256:
        raise ClassificationError(
            "ReactBench table_generator changed; review its connectivity rules and update the "
            f"frozen hash before use (observed {observed_table_hash})"
        )
    package_parent = str(reactbench_root.parent)
    if package_parent not in sys.path:
        sys.path.insert(0, package_parent)
    try:
        from ReactBench.utils.taffi_functions import table_generator
    except Exception as exc:  # dependency/import failures must be visible and fail closed
        raise ClassificationError(f"cannot import ReactBench table_generator: {exc}") from exc
    return table_generator, module_file, classifier_file


def _masked_difference(
    left: np.ndarray,
    right: np.ndarray,
    elements: Sequence[str],
) -> tuple[np.ndarray, int, int]:
    diff = np.abs(left - right)
    raw_sum = int(diff.sum())
    for index, element in enumerate(elements):
        if element.lower() in IGNORE_ELEMENTS:
            diff[index, :] = 0
            diff[:, index] = 0
    return diff, raw_sum, int(diff.sum())


def classify_intended(
    irc_log: Path,
    reference_xyz: Path,
    reactbench_root: Path = DEFAULT_REACTBENCH_ROOT,
) -> dict[str, Any]:
    """Apply ReactBench's endpoint matching logic to one Gaussian IRC log."""
    if not hasattr(np, "asarray"):
        raise ClassificationError(
            "a complete NumPy installation is required; use "
            "/home/wuping/.conda/envs/reactbench/bin/python on this system"
        )
    reactant, product = read_two_frame_xyz(reference_xyz)
    forward, reverse, log_flags = read_gaussian_irc_endpoints(irc_log)
    for endpoint in (forward, reverse):
        if endpoint.atomic_numbers != reactant.atomic_numbers:
            raise ClassificationError(
                f"{endpoint.direction} endpoint atom count/order differs from reference XYZ"
            )

    table_generator, table_generator_path, classifier_path = load_reactbench_table_generator(
        reactbench_root
    )
    elements = list(reactant.elements)
    adj_forward = table_generator(elements, forward.coordinates)
    adj_reverse = table_generator(elements, reverse.coordinates)
    adj_reactant = table_generator(elements, reactant.coordinates)
    adj_product = table_generator(elements, product.coordinates)

    endpoint_difference_raw = int(np.abs(adj_forward - adj_reverse).sum())
    comparisons: dict[str, dict[str, int]] = {}
    matrices: dict[str, np.ndarray] = {}
    for name, left, right in (
        ("forward_to_reactant", adj_forward, adj_reactant),
        ("forward_to_product", adj_forward, adj_product),
        ("reverse_to_reactant", adj_reverse, adj_reactant),
        ("reverse_to_product", adj_reverse, adj_product),
    ):
        masked, raw_sum, ignored_sum = _masked_difference(left, right, elements)
        matrices[name] = masked
        comparisons[name] = {
            "raw_adjacency_difference_sum": raw_sum,
            "difference_sum_after_ReactBench_ignore": ignored_sum,
        }

    node_map: dict[str, str | None] = {"reactant": None, "product": None}
    if endpoint_difference_raw == 0:
        reaction_type = "ConformationChange"
        reason = "IRC endpoint adjacency matrices are identical; ReactBench skips this TS"
    elif matrices["forward_to_reactant"].sum() == 0:
        node_map = {"reactant": "FORWARD", "product": "REVERSE"}
        if matrices["reverse_to_product"].sum() == 0:
            reaction_type = "Intended"
            reason = "FORWARD matches reactant and REVERSE matches product"
        else:
            reaction_type = "P_Unintended"
            reason = "reactant endpoint matches, product endpoint does not"
    elif matrices["forward_to_product"].sum() == 0:
        node_map = {"reactant": "REVERSE", "product": "FORWARD"}
        if matrices["reverse_to_reactant"].sum() == 0:
            reaction_type = "Intended"
            reason = "REVERSE matches reactant and FORWARD matches product"
        else:
            reaction_type = "R_Unintended"
            reason = "product endpoint matches, reactant endpoint does not"
    elif matrices["reverse_to_reactant"].sum() == 0:
        reaction_type = "P_Unintended"
        node_map = {"reactant": "REVERSE", "product": "FORWARD"}
        reason = "reactant endpoint matches, product endpoint does not"
    elif matrices["reverse_to_product"].sum() == 0:
        reaction_type = "R_Unintended"
        node_map = {"reactant": "FORWARD", "product": "REVERSE"}
        reason = "product endpoint matches, reactant endpoint does not"
    else:
        reaction_type = "Unintended"
        reason = "neither IRC endpoint matches the expected reactant or product"

    return {
        "status": ["DERIVED", "PARTIALLY_VERIFIED"],
        "irc_log": str(irc_log.resolve()),
        "irc_log_sha256": sha256(irc_log),
        "reference_xyz": str(reference_xyz.resolve()),
        "reference_xyz_sha256": sha256(reference_xyz),
        "reactbench_root": str(reactbench_root.resolve()),
        "reactbench_intended_classifier_source": str(classifier_path.resolve()),
        "reactbench_intended_classifier_source_sha256": sha256(classifier_path),
        "reactbench_table_generator": str(table_generator_path.resolve()),
        "reactbench_table_generator_sha256": sha256(table_generator_path),
        "criterion": "ReactBench adjacency identity with direction swap allowed",
        "reaction_type": reaction_type,
        "intended": reaction_type == "Intended",
        "reason": reason,
        "node_map": node_map,
        "ignored_elements": sorted(IGNORE_ELEMENTS),
        "endpoint_point_numbers": {
            "FORWARD": forward.point_number,
            "REVERSE": reverse.point_number,
        },
        "endpoint_adjacency_difference_sum": endpoint_difference_raw,
        "comparisons": comparisons,
        "log_diagnostic_flags_not_used_for_intended": log_flags,
        "warning": (
            "This reproduces ReactBench endpoint identity only. The printed Gaussian completion "
            "flags are diagnostics and do not gate the Intended label."
        ),
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--irc-log", type=Path, required=True, help="Gaussian IRC log")
    parser.add_argument(
        "--reference-xyz",
        type=Path,
        required=True,
        help="two-frame XYZ: expected reactant first, expected product second",
    )
    parser.add_argument(
        "--reactbench-root",
        type=Path,
        default=DEFAULT_REACTBENCH_ROOT,
        help="ReactBench package root containing utils/taffi_functions.py",
    )
    parser.add_argument("--output", type=Path, help="optional JSON output path")
    parser.add_argument("--compact", action="store_true", help="write compact JSON")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        result = classify_intended(args.irc_log, args.reference_xyz, args.reactbench_root)
    except ClassificationError as exc:
        print(json.dumps({"status": "ERROR", "reason": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 2
    indent = None if args.compact else 2
    rendered = json.dumps(result, ensure_ascii=False, indent=indent) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
